import type { Metadata } from "next";
import Navbar from "./navbar/page";
import BasketProvider from "./BasketProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container">
        <BasketProvider>
          <Navbar />
          {children}
        </BasketProvider>
      </body>
    </html>
  );
}
